bubble:
	gcc -Wall -Werror -Wextra bubble_sort.c
	./a.out
selection:
	gcc -Wall -Werror -Wextra selection_sort.c
	./a.out
insertion:
	gcc -Wall -Werror -Wextra insertion_sort.c
	./a.out
gnome:
	gcc -Wall -Werror -Wextra gnome_sort.c
	./a.out